function [fitresult, gof] = createFit(CSsave_90s, Yend_real_save_90s)
%CREATEFIT(CSSAVE_90S,YEND_REAL_SAVE_90S)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : CSsave_90s
%      Y Output: Yend_real_save_90s
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 02-Jul-2013 17:45:00


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( CSsave_90s, Yend_real_save_90s );

% Set up fittype and options.
ft = fittype( 'a/(1+(b/x))', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( ft );
opts.Display = 'Off';
opts.Lower = [0 0];
opts.StartPoint = [0.546881519204984 0.957506835434298];
opts.Upper = [Inf Inf];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );




